services:
  - type: web
    name: relay-api
    env: node
    buildCommand: npm install
    startCommand: npx tsx server/index.ts
    envVars:
      - key: NODE_VERSION
        value: "24.11.1"
      - key: SOLANA_RPC_URL
        value: "https://api.devnet.solana.com"
      - key: TEE_RPC_URL
        value: "https://tee.magicblock.app"
      - key: SKIP_TEE_VERIFICATION
        value: "true"
      - key: RELAY_ALLOWED_ORIGIN
        value: "https://your-github-pages-url"
      - key: WALLET_KEYPAIR_JSON
        sync: false
      - key: ALLOW_UNAUTHENTICATED_ADMIN
        value: "true"
      - key: ALLOW_CUSTODIAL_PAYMENT
        value: "true"
      - key: DEMO_SKIP_BUYER_CLEARANCE
        value: "true"
      - key: DEMO_DISABLE_SPL_CREATE_ESCROW
        value: "true"
      - key: PUBLISH_DEAL_TERMS_ONCHAIN
        value: "false"
      - key: ASSET_REGISTRY_COMPONENT_ID
        value: "6BE4Z9G2WkEq8AEH89FgBDDxv5517MGM1pzuzF1pZSDe"
      - key: DEAL_TERMS_COMPONENT_ID
        value: "5DTNmzUrHxbpGsj7C8U1YP1AtaHJF1qEEy2CT6W2vCqN"
      - key: CREATE_LISTING_SYSTEM_ID
        value: "7rjyGnnFRacekAxByYLiq7sXLEjScKRCbtsdnz621yMT"
      - key: MATCH_OFFER_SYSTEM_ID
        value: "EfyPjbjJ9hwuRixNH7bkT6yETnsTmEtqnQ7L3Erw9pyj"
